### ISSUE TITLE
Android Studio 3.4.0 stable release   &  library all upgrade to new stable release version 

### ISSUE THREAD

**Issue by CMingTseng** [ankitbisht/trending-git#1]
Dear Sir
Now ,Android Studio 3.4.0 stable release 
The below library all upgrade to new stable release version 
The Gradle Version upgrade to 5.1.1 & Android gradle to 3.4.0 
The Kotlin upgrade 1.3.31
The WorkManager( work-runtime) upgrade 2.0.1
your example project some void method can not run
like 
RepoDetailFragment.kt: (26, 53): Type mismatch: inferred type is Bundle? but Bundle was expected
can fixed ?
THX

**Comment by ankitbisht** [comment]
I have updated the library versions and code.
